### ISSUE TITLE
Inverted Readings 

### ISSUE THREAD

**Issue by paulbhome** [neggert/hass-egauge#316]
Hi,

When adding Individual items in the Energy Dashboard - I always get:-

Entity has a negative state
The following entities have a negative state while a positive state is expected:
sensor.egauge_todays_utility (-10.22)

I think it's because eqauge  shows usage as a negative. Any way to invert?

Many thanks

Paul

**Comment by neggert** [comment]
This integration just returns what's stored on the eGauge. If the sign is wrong, you'll need to either change the configuration on the eGauge itself or use a template sensor to create an inverted version. Something like `{{states('sensor.egauge_todays_grid_out') | float * -1}}` should work.
