### ISSUE TITLE
0.4.1 references old repo name 'egauge' causing 404s.

### ISSUE THREAD

**Issue by jdwhite** [neggert/hass-egauge#318]
## Version of the custom_component

0.4.1

## Describe the bug

Not sure when it happened, but the renaming of this repo from `egauge` to `hass-egauge` broke the "Documentation" and "Known Issues" links on the eGauge Integration page.

Presumably this will be updated in a future release, but I'm likely not the only one who be momentarily surprised to find that this repo seemingly vanished from Github.

**Comment by neggert** [comment]
This should be resolved with the 0.5.0 release. Let me know if you're still seeing any issues after updating.
