### ISSUE TITLE
Update repo references to documentation, issue_tracker in manifest.json

### ISSUE THREAD

**Issue by ckarnes** [neggert/hass-egauge#325]
Current version of custom_components/egauge/manifest.json points to a repo that doesn't exist.  HASS users get a 404 error when clicking on documentation and issues.

{
  "domain": "egauge",
  "name": "eGauge",
  "codeowners": ["@neggert"],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/neggert/egauge",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/neggert/egauge/issues",
  "requirements": ["egauge-async==0.1.2"],
  "version": "0.4.1"
}

Should be updated to:
{
...
"documentation": "https://github.com/neggert/hass-egauge",
...
 "issue_tracker": "https://github.com/neggert/hass-egauge/issues",
...
}

**Comment by neggert** [comment]
This should be resolved with the 0.5.0 release. Let me know if you're still seeing any issues after updating.
