### ISSUE TITLE
Daily energy graphs show cumulative values

### ISSUE THREAD

**Issue by jdwhite** [neggert/hass-egauge#53]
## Version of the custom_component

3.0

## Configuration

EG3000 running firmware 4.2.7
hass-egauge 3.0
HassOS 2021.9.6

EG3000 settings are unchanged:
![image](https://user-images.githubusercontent.com/1943283/133100411-d1f2902f-afab-4ae0-809e-60cf493da59d.png)

## Describe the bug

On the evening of Sept. 10, 2021, I updated HassOS from 2021.8.x to HassOS 2021.9.5 -- or possibly updating to eGauge firmware 4.2.6 -- I noticed an immediate change in how my eGauge data was showing up on home assistant.  

![image](https://user-images.githubusercontent.com/1943283/133100811-c0ecf3bb-5d44-4bc5-9794-c99f09aeec6f.png)

Data is now showing as cumulative throughout the day plus the first hour of the new day still has the last day's data. From today: 
![image](https://user-images.githubusercontent.com/1943283/133096884-09ad0a99-b7bd-4d5e-8f9d-9336f531505e.png)

Unfortunately, I updated the EG3000 firmware and HassOS in the same evening so I don't know which is to blame. I re-installed hass-egauge 3.0.

I saw that eGauge released 4.2.7 recently, so installed that last night but has not changed my graphs.
Also been keeping up with HassOS releases but that has not changed anything either.

Has anyone else noticed a change between 2021.8.x and 2021.9.x or newer eGauge firmware?

**Comment by neggert** [comment]
Hmm, they definitely changed some APIs in 2021.9 (see #50), but they claimed that nothing would *break* until 2021.11. Guess I better get on this soon.

FWIW, I've been on eGauge 4.2.7 for a while, so I doubt that's the problem.

**Comment by phidauex** [comment]
Yeah, I noticed this too - regenerated my entities just in case, but still have the same issue. The data from the eGauge appears correct - the values are gradually increasing showing cumulative energy until it resets at the end of the day. But the Energy panel now appears to be treating it like an instantaneous measurement and just adding it up.

**Comment by neggert** [comment]
There's a fix up on the master branch if you want to give it a shot. I'm going to run it myself for a few days before I tag a release.

**Comment by jdwhite** [comment]
Master branch from last night did the trick. Thanks, Nic.

**Comment by neggert** [comment]
Released v0.4.0, which includes the fix.
