### ISSUE TITLE
Needing more information

### ISSUE THREAD

**Issue by billraff** [neggert/hass-egauge#8]
I've been using REST to get information from my egauge into HA using the help I received from this thread -

https://community.home-assistant.io/t/egauge-power-meter-sensors-over-local-rest-api/230209

I wanted to try your implementation so installed the component via HACS and restarted HA. Your instructions state to configure through the UI but I'm not seeing a UI. Do I need to somehow add something additional in order to get to the place where I enter my URL and credentials? 
I'm not a very technical person and my HA is pretty basic. Thanks for any assistance.

**Comment by neggert** [comment]
Once you've added the component, you need to actually add your device to HA. In HomeAssistant, go to Configuration -> Integrations -> Add Integration (blue button on the lower right). Search for eGauge, click on the the integration, and it should take you to the configuration screen.

**Comment by billraff** [comment]
Thanks. That was where I was stuck. All good now.
